# Generated by Django 5.0.7 on 2024-07-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0002_roommember'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommember',
            name='member',
            field=models.BooleanField(default=False),
        ),
    ]
